### ISSUE TITLE
API : 記事情報取得API修正

### ISSUE THREAD

**Issue by ShutoKeisuke** [memorandum-app/memorandum-app-api#9]
記事情報でcontentがnullの部分を排除してレスポンスを送るように変更

**Comment by YukiOct** [comment]
### RequestToTest
記事情報でcontentがnullの部分を排除してレスポンスを送るかどうかを確認

### 環境
phase : ph1

### エビデンス
https://onedrive.live.com/?authkey=%21AM%5FsLb880ZKtEHc&id=2E42114F6636414A%21455&cid=2E42114F6636414A
